services:
  income-db:
    image: postgres:12-bullseye
    restart: always
    # command: -c ssl=on -c ssl_cert_file=/etc/ssl/certs/ssl-cert-snakeoil.pem -c ssl_key_file=/etc/ssl/private/ssl-cert-snakeoil.key
    environment:
      POSTGRES_DB: ${DB_NAME_INCOME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ./data-income:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - mynet
  management-db:
    image: postgres:12-bullseye
    restart: always
    # command: -c ssl=on -c ssl_cert_file=/etc/ssl/certs/ssl-cert-snakeoil.pem -c ssl_key_file=/etc/ssl/private/ssl-cert-snakeoil.key
    environment:
      POSTGRES_DB: ${DB_NAME_MANAGEMENT}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ./data-management:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    networks:
      - mynet
  report-db:
    image: postgres:12-bullseye
    restart: always
    # command: -c ssl=on -c ssl_cert_file=/etc/ssl/certs/ssl-cert-snakeoil.pem -c ssl_key_file=/etc/ssl/private/ssl-cert-snakeoil.key
    environment:
      POSTGRES_DB: ${DB_NAME_REPORT}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ./data-report:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    networks:
      - mynet
  pgadmin4:
    image: elestio/pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PDADMIN_USER}
      PGADMIN_DEFAULT_PASSWORD: ${PDADMIN_PASSWORD}
      PGADMIN_LISTEN_PORT: 8080
    ports:
      - "8081:8080"
    volumes:
      - ./data-pgadmin:/pgadmin4/servers.json
    networks:
      - mynet
  income-server:
    image: sebacassone/income-server:latest
    restart: always
    environment:
      DB_HOST: income-db:5432
      DB_NAME: ${DB_NAME_INCOME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3001:3001"
    networks:
      - mynet
  management-server:
    image: sebacassone/management-server:latest
    restart: always
    environment:
      DB_HOST: management-db:5432
      DB_NAME: ${DB_NAME_MANAGEMENT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3002:3002"
    networks:
      - mynet
  report-server:
    image: sebacassone/report-server:latest
    restart: always
    environment:
      DB_HOST: report-db:5432
      DB_NAME: ${DB_NAME_REPORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3003:3003"
    networks:
      - mynet
  config-server:
    image: sebacassone/config-server:latest
    restart: always
    environment:
      GITHUB_TOKEN: ${GITHUB_TOKEN}
    ports:
      - "8888:8888"
    networks:
      - mynet
  gateway-server:
    image: sebacassone/gateway-server:latest
    restart: always
    ports:
      - "8080:8080"
    networks:
      - mynet

networks:
  mynet:
    driver: bridge

volumes:
  data-income:
  data-management:
  data-report:
  data-pgadmin:
