server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/sebacassone/loan-data-diinf
          username: sebacassone
          password: ${GITHUB_TOKEN}
          search-paths: config-data
  application:
    name: config-server
